name: DevOps Homework

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - main  # Также запускать при создании pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Запускаем сборку на Linux

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'          # Указываем версию Java
          distribution: 'temurin'     

      # Шаг 3: Установить зависимости и собрать проект
      - name: Install dependencies and build
        run: mvn install -DskipTests

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: mvn test
