name: DevOps Homework

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - main  # Также запускать при создании pull request в ветку main

jobs:
  # Джоба 1: Сборка проекта
  build:
    runs-on: ubuntu-latest  # Запускаем сборку на Linux

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'          # Указываем версию Java
          distribution: 'temurin'     

      # Шаг 3: Установить зависимости и собрать проект
      - name: Install dependencies and build
        run: mvn install -DskipTests

  # Джоба 2: Запуск тестов
  test:
    needs: build  # Зависимость: выполняется только после успешной сборки
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг 3: Запуск тестов
      - name: Run tests
        run: mvn test

  # Джоба 3: Деплой на сервер
  deploy:
    needs: test  # Зависимость: выполняется только после успешного тестирования
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      # Шаг 3: Деплой на сервер
      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
          cd /home/user1/test/devOps
          git pull origin main
          mvn clean package -DskipTests
          java -jar target/devOps-0.0.1-SNAPSHOT.jar
          EOF
